### ISSUE TITLE
Formatter fails 

### ISSUE THREAD

**Issue by eiswind** [develar/d2-intellij-plugin#10]
I did not see any hints in the logs, but when I hit CMD-L (Format on linux) I get an error popup and it does not format.

![Bildschirmfoto vom 2024-01-09 10-12-07](https://github.com/develar/d2-intellij-plugin/assets/1238044/ed044cee-6ced-4955-aa7a-44ef074e159d)

**Comment by develar** [comment]
Do you use the latest plugin version `1.3.0`?

**Comment by eiswind** [comment]
After updating it 's working! Thx again.
